const CREATED = 201;
const BAD_REQUEST_ERR = 400;
const UNAUTHORIZED_ERR = 401;
const FORBIDDEN_ERR = 403;
const NOT_FOUND_ERR = 404;
const CONFLICT_ERR = 409;
const INTERNAL_SERVER_ERR = 500;

module.exports = {
  CREATED,
  BAD_REQUEST_ERR,
  UNAUTHORIZED_ERR,
  FORBIDDEN_ERR,
  NOT_FOUND_ERR,
  CONFLICT_ERR,
  INTERNAL_SERVER_ERR,
};
